### ISSUE TITLE
我请求订单列表的时候应该是把用户的id发给你，你返回给我该用户的所有订单

### ISSUE THREAD

**Issue by xiaowu4** [SeanChense/fast-order#1]
你写的是获取所有用户的吗

**Comment by SeanChense** [comment]
不是，登录着哪个用户的账户，就返回哪个用户的所有订单。带上 Cookie，Cookie 里写好
`authed=TOKEN`
就行了

**Comment by xiaowu4** [comment]
cookie里面写authed = TOKEN是啥意思
我的请求是在header里面添加了token = “tokenString”

**Comment by SeanChense** [comment]
没事，这是我之前的设计错误。导致原来的实现在 web 上没法儿兼容。所以我改了，但是给你的 api 上还没改成 cookie
你想用 Cookie 这种方式还是自定义一个 token：TOEKN_STR 的 header 的方式？

**Comment by xiaowu4** [comment]
还是 token：TOEKN_STR 的 header 的方式这样吧，因为我全部写成这样的了
